
- src: git@github.com:blunix/role-docker.git
  version: 1.1.0
  name: blunix.role-docker
  scm: git

- src: git@github.com:blunix/role-gitlab.git
  version: feature/init
  name: blunix.role-gitlab
  scm: git
